[package]
name = "iron-chip"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
minifb = "0.28.0"
log = "0.4.28"
pretty_env_logger = "0.5.0"
rand = "0.9.2"